# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "picturefill-rails"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-08-29"
  s.description = "Use picturefill with Rails :)"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/picturefill-rails.rb",
    "lib/picturefill/engine.rb",
    "lib/picturefill/view_helper.rb",
    "picturefill-rails.gemspec",
    "spec/picturefill/view_helper_spec.rb",
    "spec/spec_helper.rb",
    "spec/srcset/banner-HD.jpeg",
    "spec/srcset/banner-phone-HD.jpeg",
    "spec/srcset/banner-phone.jpeg",
    "spec/srcset/banner.jpeg",
    "spec/srcset/index.html",
    "spec/srcset/tests/index.html",
    "spec/srcset/tests/srcset-tests.js",
    "spec/srcset/view_helper_spec.rb",
    "vendor/assets/javascripts/jquery-picture.js",
    "vendor/assets/javascripts/jquery-picture.min.js",
    "vendor/assets/javascripts/picturefill.js",
    "vendor/assets/javascripts/picturefill/matchmedia.js",
    "vendor/assets/javascripts/srcset.js",
    "vendor/assets/javascripts/srcset.min.js"
  ]
  s.homepage = "http://github.com/kristianmandrup/picturefill-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Picturefill view helpers for Rails to facilitate Responsive Images"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

